
 var GAME_LEVELS = [
  ["                                       y                  yyyy                  ",
   "                                      yyy                                       ",
   "                            y                                                   ",
   "       y      y            yyy                                                  ",
   "      y y    y y                                                                ",
   "     yyyyyyyyyyyy                                                   o           ",
   "                                                    o      o       xxx          ",
   "                                             o      xxx    xxx    x!!!x        ",
   "                                            xxx                   x!!!x         ",
   "                                     o o                          xx!xx      e  ",
   "                                  xxxxx                            xvx          ",
   " @                                                                              ",
   "xxxx                                                                   xxxx  o  ",
   "   x                    o                                              x  x  o  ",
   "   x                           o                             oooo      x  x  o  ",
   "   x          xx   xx         xx                   xxx     xxxxxxxxxxxxx  xxxxxx",
   "   x          x!!!!!x                      o       x x!!!!!x                    ",
   "   xxxxxtxxxxxx!!!!!xxxxxxxx      xxxxxxx  x  xxxxxx xxxxxxx                    ",
   "                           x  !!  x     x     x                                 ",
   "                           x !!!! x     x!!!!!x      yyyy                       ",
   "                           x!!!!!!x     x!!!!!x     yyyyyy                      ",
   "                           xxxxxxxx     xxxxxxx      y  y                       ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             !!x  ",
   "                                                                                                             !!x  ",
   "                                         xxxxxxxxxx                                                          !!x  ",
   "                                        xx!!!!!!!!xx                                                         !!x  ",
   "                                         xxxxxxxx!!x                                              o   o   o  !!x  ",
   "                                                xx!x               o   o                            |   |   xx!x  ",
   "                                                 x!x                                          xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx               x   x                  |     !!!!!!!!!!!!!!xx  ",
   "                                                                 |       |  xx          xxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                               x!!!!! !!!!x               v                       ",
   "                                                                xxxxxxxxxx                                        ",
   "                                               x                  xxxxxxx        xxx                              ",
   "                                               x                                                                  ",
   "                                               x     xx                                                           ",
   "                                               x     x                             xx                             ",
   "                                               xx    x                                                            ",
   "                                               x     x      o | o                                                 ",
   "                                               x     x      @                                                     ",
   "                                               x     x     xxxxxx            xxxxxxxxx                            ",
   "      e                           o            x    xx                                                            ",
   "                                               x     x             xxx                                            ",
   "     xx      x                       x         x     x                   xxxxx   xxxxxx                           ",
   "            xx         xx     xx  o  xx    x   x     x               x     o     xxx                              ",
   "!!!!!!!!!!!!!x         xx!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!    x     =     xxx         x                    ",
   "!!!!!!!!!!!!!xx        xx!!!!!xx      xxxxxxxxxx     x!!!!!!!xx!!    xxxxxxxxxxxxxxxxx  o o  xx                   ",
   "!!!!!!!!!!!!!xx   o   xxx!!!!!x    o                 xx!!!!!!xx                      xx     xx                    ",
   "!!!!!!!!!!!!!xxx     xxxx!!!!!x                     xx!!!!!!xx                        xx   xx                     ",
   "!!!!!!!!!!!!!xxxxxxxxxxxx!!!!!xx  =    xxxxxxxxxxxxxx!!!!!!xx                                                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                            ttt                       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
