var GAME_LEVELS = [
  ["                                       y                  yyyy                  ",
   "                                      yyy                                       ",
   "                            y                                                   ",
   "       y      y            yyy                                                  ",
   "      y y    y y                                                                ",
   "     yyyyyyyyyyyy                                                   o           ",
   "                                                    o      o       xxx          ",
   "                                             o      xxx    xxx    x!!!x         ",
   "                                            xxx                   x!!!x         ",
   "                                     o o                          xx!xx      e  ",
   "                                  xxxxx                            xvx          ",
   " @                                                                              ",
   "xxxx                                                                   xxxx  o  ",
   "   x                    o                                              x  x  o  ",
   "   x                           o                             oooo      x  x  o  ",
   "   x          xx   xx         xx                   xxx     xxxxxxxxxxxxx  xxxxxx",
   "   x          x!!!!!x                      o       x x!!!!!x                    ",
   "   xxxxxtxxxxxx!!!!!xxxxxxxx      xxxxxxx  x  xxxxxx xxxxxxx                    ",
   "                           x  !!  x     x     x                                 ",
   "                           x !!!! x     x!!!!!x      yyyy                       ",
   "                           x!!!!!!x     x!!!!!x     yyyyyy                      ",
   "                           xxxxxxxx     xxxxxxx      y  y                       ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             !!x  ",
   "                                                                                                             !!x  ",
   "                                         xxxxxxxxxx                                                          !!x  ",
   "                                        xx!!!!!!!!xx                                                         !!x  ",
   "                                         xxxxxxxx!!x                                              o   o   o  !!x  ",
   "                                                xx!x               o   o                            |   |    !!x  ",
   "            yyyy          yyyy                   x!x                                          xxxxxxxxxxxxxxx!!x  ",
   "           yyyyyy        yyyyyy                  xvx               x   x                  |     !!!!!!!!!!!!!!xx  ",
   "            yyyy          yyyy                                   |       |  xx          xxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                               x!!!!! !!!!x               v                       ",
   "                                                                xxxxxxxxxx                                        ",
   "                    yyyy                       x                  xxxxxxx        xxx                              ",
   "                   yyyyyy                      x                                                                  ",
   "                    yyyy                       x     xx                                                           ",
   "                                               x     x                             xx            yyyy             ",
   "                                               xx    x                                          yyyyyy            ",
   "                                               x     x      o | o                                yyyy             ",
   "                                               x     x      @                                                     ",
   "                                               x     x     xxxxxx            xxxxxxxxx                            ",
   "      e                           o            x    xx                                                            ",
   "                                               x     x             xxx                                            ",
   "    xxxx     x                       x         x     x                   xxxxx   xxxxxx                           ",
   "            xx         xx     xx  o  xx    x   x     x               x     o     xxx                              ",
   "!!!!!!!!!!!!!x         xx!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!    x     =     xxx         x                    ",
   "!!!!!!!!!!!!!xx        xx!!!!!xx      xxxxxxxxxx     x!!!!!!!xx!!    xxxxxxxxxxxxxxxxx  o o  xx                   ",
   "!!!!!!!!!!!!!xx   o   xxx!!!!!x    o                 xx!!!!!!xx                      xx     xx                    ",
   "!!!!!!!!!!!!!xxx     xxxx!!!!!x                     xx!!!!!!xx                        xx   xx                     ",
   "!!!!!!!!!!!!!xxxxxxxxxxxx!!!!!xx  =    xxxxxxxxxxxxxx!!!!!!xx                                                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                            ttt                       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                           x      x                           ",
   "                                                                           x      x                           ",
   "                                           o                               x      x                           ",
   "                                         @                          x      x      x       x                   ",
   "                                        xxxxx                        xxxxxxxxxxxxxxxxxxxxxx                   ",
   "                                         xxx                                                                  ",
   "                                         xxx                                                                  ",
   "                                         xxx                                 yyeyy                            ",
   "                                       xxxxxxx                               yyyyy                            ",
   "                                       x!!!!!x                                yyy                             ",
   "                                     o x!!!!!x o                               y                              ",
   "                                     xxx!!!!!xxx                           o   y    o                         ",
   "                                       x!!!!!x                             xx  y   xx                         ",
   "                                       x!!!!!x                       xx  |     |     |   xx                   ",
   "                                       x!!!!!x       |    |           xx!!!!!!!!!!!!!!!!xx                    ",
   "                                       xxv!xxxx                         xxxx!!!!!!!!xxx                       ",
   "                                          !  xxxx  xxx   xxxxxxxx                                             ",
   "                                          !  x           x                                                    ",
   "                                          !  x           x                                                    ",
   "                                          !  x           x                                                    ",
   "                                          !  x= = = =    x     o                                              ",
   "                                          !  x           x                                                    ",
   "                                 o o      !  x    = = = =x     x                                              ",
   "                                  x       !              x     v          o                                   ",
   "                                 xxx      v              x                                                    ",
   "                                 xxx                     x                x                                   ",
   "                             xxxxxxxxx                   x         xxxx   v                                   ",
   "                             x                      xxxxxx                                                    ",
   "                             x = = = = =     x               xxxx                                             ",
   "                             xxxxx           x                                                                ",
   "  xxx                                o       xxxxxxxxxxxxx                                                    ",
   "  x x                                o                                                                        ",
   "  x                                  o                         xxxxx                                 o        ",
   "  x                                                                                                           ",
   "  x                                                                                           o      x        ",
   "  x      x       x      x                           |xxxx|    |    |     xxxxxx               x     xxx       ",
   "  x     xxx     xxx    xxx               o o                                        xxx      xxx    xxx       ",
   "  x    oxxxo    xxx    xxx            xx                                                     xxx   xxxxx    o ",
   "  x    xxxxx   xxxxx  xxxxx                  xxx                                            xxxxx    x      o ",
   "  x      x       x      x      xxxxxxxxxxxxx                                                  x      x      o ",
   "  x      x       x      x      x= = = =                   xxxx                                x      x        ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxtt",
   "                                                                                                              ",
   "                                                                                                              "],
   ["                                                                                ",
    "           y     y yyyyyyy y     y   y         y   yyyyyyy  yy      y           ",
    "            y   y  y     y y     y   y         y      y     y y     y           ",
    "             y y   y     y y     y   y         y      y     y  y    y           ",
    "              y    y     y y     y   y    y    y      y     y   y   y           ",
    "              y    y     y y     y   y   y y   y      y     y    y  y           ",
    "      o       y    y     y y     y   y  y   y  y      y     y     y y           ",
    "              y    yyyyyyy yyyyyyy   yyy     yyy   yyyyyyy  y      yy           ",
    "                                                                                ",
    "        o                                                  o      o             ",
    "   e                  o    o                        o          o                ",
    " @            o       o                                                         ",
    "xxxx    o                      o            o        o     o      o     xxxx  o ",
    "   x                    o            o           o                      x!!x  o ",
    "   x oo                        o      o  o              o       oooo    x!!x  o ",
    "   x       oo xxxxxxx      oooooooo     o         oooxxxxxxxxxxxxxxxxxxxx!!xxxxx",
    "   x   ooooo  x!!!!!x      xxxxxxxxoooooooooooooooooox!!!!!x!!!!!!!!!!!!!!!!!!!!",
    "   xxxxxxxxxxxx!!!!!xxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
